package com.example.Techwing.models;
public enum SessionStatus {
    PENDING, TECHNICAL_IN_PROGRESS, TECHNICAL_COMPLETE,
    CODING_IN_PROGRESS, CODING_COMPLETE,
    HR_IN_PROGRESS, HR_COMPLETE,
    EVALUATING, COMPLETED, ABANDONED
}
