spring.application.name=Techwing_AI_interview_platform
server.port=8080






spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://venkat.czwke0g4e5rn.ap-south-1.rds.amazonaws.com/techwing_ai
spring.datasource.username=venkatvs
spring.datasource.password=venkatvs56


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.flyway.enabled=false


jwt.secret=techwings_super_secret_key_change_in_production_min_256_bits
jwt.access-token-expiry-ms=7200000
jwt.refresh-token-expiry-ms=604800000


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB


aws.region=ap-south-1
aws.s3.bucket.resumes=techwings-resumes
aws.s3.bucket.reports=techwings-reports
aws.s3.bucket.audio=techwings-audio
aws.access-key=YOUR_ACCESS_KEY
aws.secret-key=YOUR_SECRET_KEY


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


ai.service.base-url=https://techwing-ai-interview.onrender.com


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


logging.level.com.example.Techwing=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
